name: Update Projects JSON

on:
  push:
    paths:
      - 'codes/**'            # Trigger when files are added or modified in the codes/ directory
      - 'update_projects.py'  # Trigger when the script itself is modified

permissions:
  contents: write

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # 3. Install Dependencies
      - name: Install Pygments
        run: pip install pygments

      # 4. Run the Python Script
      - name: Run update_projects.py
        run: python update_projects.py

      # 5. Commit and Push Changes
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add projects.json web_projects/*
          git commit -m "Automated update of projects.json and HTML files" || echo "No changes to commit"
          git push
